### PR TITLE
added popd to exit working directory set by pushd.

### PR DESCRIPTION
**Pull request by RaiBishal**
Ticket: https://github.com/ISISComputingGroup/IBEX/issues/5208

### CODE REVIEW

**Comment by FreddieAkeroyd** [comment]
Please can you test if removing pushd and just using
```
set KITS_ICP_PATH=\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP
```
in define_latest_genie_python.bat works

**Comment by RaiBishal** [comment]
> Please can you test if removing pushd and just using
> 
> ```
> set KITS_ICP_PATH=\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP
> ```
> 
> in define_latest_genie_python.bat works
It seems to work however, it is really slow. It could also be due to VPN.

**Comment by FreddieAkeroyd** [comment]
I would guess it is vpn, the data is coming from the same place in both cases, it is just you don't have a mapped drive letter

**Comment by FreddieAkeroyd** [comment]
Tested on NDXDEMO

**Pull request merged**
